//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalBachelorNeer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admininfo
    {
        public int o_ID { get; set; }
        public string o_Name { get; set; }
        public string o_Number { get; set; }
        public string o_Email { get; set; }
        public string o_Adress { get; set; }
        public string o_NID { get; set; }
        public string o_Password { get; set; }
    }
}
