//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalBachelorNeer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Approvedproperty
    {
        public int ap_Id { get; set; }
        public string ap_Name { get; set; }
        public string ap_Email { get; set; }
        public string ap_Number { get; set; }
        public string ap_Type { get; set; }
        public string ap_Proaddress { get; set; }
        public string ap_Thana { get; set; }
        public string ap_Imfile { get; set; }
        public Nullable<double> ap_Rent { get; set; }
        public Nullable<int> ap_Bed { get; set; }
        public Nullable<int> ap_Bath { get; set; }
        public Nullable<int> ap_Kitchen { get; set; }
        public Nullable<int> ap_Belcony { get; set; }
        public Nullable<int> ap_Dining { get; set; }
    }
}
