//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalBachelorNeer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyDetail
    {
        public int up_ID { get; set; }
        public string up_Name { get; set; }
        public string up_Email { get; set; }
        public string up_Number { get; set; }
        public string up_Type { get; set; }
        public string up_Proaddress { get; set; }
        public string up_Thana { get; set; }
        public string up_Imfile { get; set; }
        public Nullable<double> up_Rent { get; set; }
        public Nullable<int> up_Bed { get; set; }
        public Nullable<int> up_Bath { get; set; }
        public Nullable<int> up_Kitchen { get; set; }
        public Nullable<int> up_Belcony { get; set; }
        public Nullable<int> up_Dining { get; set; }
    }
}
