//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalBachelorNeer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userinfo
    {
        public int u_ID { get; set; }
        public string u_Name { get; set; }
        public string u_Number { get; set; }
        public string u_Email { get; set; }
        public string u_Adress { get; set; }
        public string u_NID { get; set; }
        public string u_Password { get; set; }
    }
}
